# This is a basic workflow that is manually triggered to update the snes9x libretro core for aarch64

name: ArkOS Kernel with Logo Generator

on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job.
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout_repo
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
        fetch-depth: 1
    - name: checkout kernel repo selected
      id: Build_kernel_with_new_logo
      shell: bash {0}
      run: |
        sudo apt -y update
        sudo apt -y install build-essential git lzop build-essential gcc bc libncurses5-dev libc6-i386 lib32stdc++6 zlib1g netpbm
        if [[ ${GITHUB_REF##*/} == "main" ]]; then
           whichgit="rg503Kernel"
        else
           whichgit="RG353VKernel"
        fi
        git clone --depth=1 --recursive https://github.com/christianhaitian/${whichgit}.git
        mkdir -p ./prebuilts/gcc/linux-x86/aarch64/
        wget https://releases.linaro.org/components/toolchain/binaries/6.3-2017.05/aarch64-linux-gnu/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu.tar.xz
        tar Jxvf gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu.tar.xz -C ./prebuilts/gcc/linux-x86/aarch64/
        cd ${whichgit}
        cp ../cod_ghost.png .
        pngtopnm cod_ghost.png | ppmquant 224 | pnmnoraw > drivers/video/logo/logo_linux_clut224.ppm
        make ARCH=arm64 rk3566_optimized_linux_defconfig && make ARCH=arm64 KERNEL_DTS=rk3566 KERNEL_CONFIG=rk3566_optimized_linux_defconfig -j2
    - name: Get kernel artifact
      uses: actions/upload-artifact@v3
      with:
        name: image
        path: ${whichgit}/arch/arm64/boot/Image
